### ISSUE TITLE
Missing file 'res://addons/advanced-text/MarkupTextEditor/FileRam.gd'

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [rakugoteam/AdvancedText#63]
https://github.com/rakugoteam/AdvancedText/blob/bb639474760a631266d455c1b7297c544f64b544/project.godot#L81

This file is missing from the repository and cannot be loaded.

**Comment by Jeremi360** [comment]
Oh, my bad, I probably didn't pushed updated *project.godot*, *FileRam.gd* is now *EditorHelper.gd*

**Comment by Jeremi360** [comment]
fixed in #63 at `1.6` branch
